version: '3'
services:
  assassin:
    hostname: assassin
    container_name: assassin
    volumes:
      - ..:/app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
volumes:
  .:
